CREATE TABLE IF NOT EXISTS events (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(100),
    speaker VARCHAR(255),
    banner_image TEXT,
    location VARCHAR(255) NOT NULL,
    event_date TIMESTAMP WITH TIME ZONE NOT NULL,
    quota INT NOT NULL CHECK (quota >= 0),
    status event_status DEFAULT 'draft' NOT NULL,
    created_by UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_events_creator FOREIGN KEY (created_by) 
        REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE events ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE events ADD COLUMN IF NOT EXISTS speaker VARCHAR(255);
ALTER TABLE events ADD COLUMN IF NOT EXISTS banner_image TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE events ADD COLUMN IF NOT EXISTS rejection_reason TEXT DEFAULT NULL;